name: Maven Deploy to Artifactory

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
           java-version: 11
           distribution: 'temurin'
           server-password: ${{ secrets.GITHUB_TOKEN }}
    

      - name: Configure Maven settings 
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>snapshots</id><username>${{ secrets.ARTIFACTORY_USERNAME }}</username><password>${{ secrets.ARTIFACTORY_PASSWORD }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build and deploy to Artifactory
        uses: jfrog/setup-jfrog-cli@v2
        with:
          version: 'latest'

      - name: Configure Maven for Artifactory
        run: |
          jf mvn-config --server-id-resolve snapshots \
                  --server-id-deploy snapshots \
                  --repo-resolve-releases mvn-project-libs-release \
                  --repo-resolve-snapshots mvn-project-libs-snapshot \
                  --repo-deploy-releases mvn-project-libs-release \
                  --repo-deploy-snapshots mvn-project-libs-snapshot
        env:
         JFROG_USER: ${{ secrets.ARTIFACTORY_USERNAME }}
         JFROG_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
         JFROG_URL: ${{ secrets.ARTIFACTORY_URL }}
         
      - name: Run Maven deploy
        run: |
          jf mvn clean deploy -f pom.xml
